### ISSUE TITLE
Unexpected token - GZipped responses cause Eureka interactions to fail

### ISSUE THREAD

**Issue by brandongk60** [jquatier/eureka-js-client#54]
When the server returns GZipped responses, they are parsed to JSON before being unzipped.  This produces an error:

REQUEST emitting complete http://192.168.99.100:8080/eureka/v2/apps/
retrieved registry successfully

SyntaxError: Unexpected token 
    at Object.parse (native)
    at Request._callback (/Users/brandongk/Desktop/old-freshgrade/eureka-js-client/lib/EurekaClient.js:370:41)
    at Request.self.callback (/Users/brandongk/Desktop/old-freshgrade/eureka-js-client/node_modules/request/request.js:200:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/brandongk/Desktop/old-freshgrade/eureka-js-client/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/brandongk/Desktop/old-freshgrade/eureka-js-client/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

**Comment by brandongk60** [comment]
PR #55.

**Comment by jquatier** [comment]
Fixed in #55 and available in v2.5.1. Thanks!

**Comment by jquatier** [comment]
For posterity... It looks like in later versions of Eureka it ignores the `Accept-Encoding` header and always sends gzipped content down no matter what. This was added in August of 2015 due to the size of the response and most modern clients/browsers supporting gzip. So, that's probably why this is an issue now, because even though we weren't sending `Accept-Encoding: gzip`, later Eureka versions send gzipped data. More info [here](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/GzipEncodingEnforcingFilter.java) if you want to check it out.
