### ISSUE TITLE
eureka registration FAILED: status: 404 body: undefined

### ISSUE THREAD

**Issue by danielbayerlein** [jquatier/eureka-js-client#62]
Hi @jquatier,

I have a problem with the register of an application.

```
node server.js

Error: eureka registration FAILED: status: 404 body: undefined
    at Request._callback (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/eureka-js-client/lib/EurekaClient.js:235:25)
    at Request.self.callback (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

Eureka 1.4.6 runs on http://localhost:8761/

_server.js_
```javascript
const express = require('express');
const exphbs = require('express-handlebars');
const app = express();

app.engine('handlebars', exphbs({ layout: false }));
app.set('view engine', 'handlebars');

app.get('/footer', (req, res) => {
  res.render('footer', {
    year: new Date().getFullYear(),
  });
});

app.listen(3001);

// -----------------------------------------------

const Eureka = require('eureka-js-client').Eureka;
const client = new Eureka({
  instance: {
    app: 'static-ui',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    port: 3001,
    vipAddress: 'static-ui.danielbayerlein.de',
    dataCenterInfo: {
      name: 'Static UI',
    },
  },
  eureka: {
    host: 'localhost',
    port: 8761,
  },
});

client.logger.level('debug');

client.start((error) => {
  console.log(error || 'complete');
});
```

_package.json_
```json
{
  "name": "static-ui",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Daniel Bayerlein",
  "license": "MIT",
  "dependencies": {
    "eureka-js-client": "^2.5.2",
    "express": "^4.13.4",
    "express-handlebars": "^3.0.0"
  },
  "devDependencies": {
    "eslint": "^2.9.0",
    "eslint-config-airbnb-base": "^2.0.0",
    "eslint-plugin-import": "^1.7.0"
  }
}
```

Any idea?

**Comment by jquatier** [comment]
For one, `dataCenterInfo.name` is not a valid value. Try setting it to `MyOwn` because the server uses that to map it to the right config type. I would also turn on debug, `NODE_DEBUG=request node app.js` to see that URLs it's hitting. Make sure you can hit your eureka server at localhost:8671/eureka. Post yhe full debug log if you are still having issues.

**Comment by danielbayerlein** [comment]
```
NODE_DEBUG=request npm start

> static-ui@1.0.0 start /Users/danielbayerlein/Projects/micro-ui/static-ui
> node server.js

REQUEST { url: 'http://localhost:8761/eureka/v2/apps/static-ui',
  json: true,
  body:
   { instance:
      { app: 'static-ui',
        hostName: 'localhost',
        ipAddr: '127.0.0.1',
        port: 3001,
        vipAddress: 'static-ui.danielbayerlein.de',
        dataCenterInfo: [Object],
        status: 'UP' } },
  gzip: true,
  callback: [Function],
  method: 'POST' }
REQUEST make request http://localhost:8761/eureka/v2/apps/static-ui
REQUEST onRequestResponse http://localhost:8761/eureka/v2/apps/static-ui 404 { server: 'Apache-Coyote/1.1',
  'content-length': '0',
  date: 'Sun, 08 May 2016 18:50:48 GMT',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function http://localhost:8761/eureka/v2/apps/static-ui
REQUEST response end http://localhost:8761/eureka/v2/apps/static-ui 404 { server: 'Apache-Coyote/1.1',
  'content-length': '0',
  date: 'Sun, 08 May 2016 18:50:48 GMT',
  connection: 'close' }
REQUEST end event http://localhost:8761/eureka/v2/apps/static-ui
REQUEST invalid JSON received http://localhost:8761/eureka/v2/apps/static-ui
REQUEST emitting complete http://localhost:8761/eureka/v2/apps/static-ui
Error: eureka registration FAILED: status: 404 body: undefined
    at Request._callback (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/eureka-js-client/lib/EurekaClient.js:235:25)
    at Request.self.callback (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/danielbayerlein/Projects/micro-ui/static-ui/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

The Eureka-GUI is accessible at http://localhost:8761. Is that the problem?

**Comment by jquatier** [comment]
That could be the issue. Perhaps your setup has eureka under the root instead of `/eureka`. If you hit `http://localhost:8761/v2/apps` do you get the service response? If so, set `eureka.servicePath` in your config to `/v2/apps` instead of the default `/eureka/v2/apps`.

**Comment by danielbayerlein** [comment]
http://localhost:8761/v2/apps returns 404, too.

My Eureka-Server is a simple Spring-Boot application with the spring-cloud-starter-eureka-server dependency.

**Comment by jquatier** [comment]
I looked up the Spring Cloud docs and it looks like the REST service is hosted at: http://localhost:8761/eureka/apps


Assuming that URL works in your browser, set `eureka.servicePath` in your config to `/eureka/apps`

**Comment by danielbayerlein** [comment]
Oh sorry - RTFM ...

Now I get a 400 Bad Request from the Eureka server. I followed your instructions at known issues.

My current configuration:

```javascript
const Eureka = require('eureka-js-client').Eureka;
const client = new Eureka({
  instance: {
    app: 'static-ui',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    port: {
      '$': 3001,
      '@enabled': true,
    },
    vipAddress: 'static-ui.danielbayerlein.de',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/',
  },
});
client.logger.level('debug');
client.start((error) => {
  console.log(error || 'complete');
});
```

The console output from the Node.js server:

```
REQUEST { url: 'http://localhost:8761/eureka/apps/static-ui',
  json: true,
  body:
   { instance:
      { app: 'static-ui',
        hostName: 'localhost',
        ipAddr: '127.0.0.1',
        port: [Object],
        vipAddress: 'static-ui.danielbayerlein.de',
        dataCenterInfo: [Object],
        status: 'UP' } },
  gzip: true,
  callback: [Function],
  method: 'POST' }
REQUEST make request http://localhost:8761/eureka/apps/static-ui
REQUEST onRequestResponse http://localhost:8761/eureka/apps/static-ui 204 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/json',
  date: 'Mon, 09 May 2016 18:10:16 GMT',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function http://localhost:8761/eureka/apps/static-ui
REQUEST response end http://localhost:8761/eureka/apps/static-ui 204 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/json',
  date: 'Mon, 09 May 2016 18:10:16 GMT',
  connection: 'close' }
REQUEST end event http://localhost:8761/eureka/apps/static-ui
REQUEST invalid JSON received http://localhost:8761/eureka/apps/static-ui
REQUEST emitting complete http://localhost:8761/eureka/apps/static-ui
registered with eureka:  static-ui/localhost
REQUEST { url: 'http://localhost:8761/eureka/apps/',
  headers: { Accept: 'application/json' },
  gzip: true,
  callback: [Function],
  method: 'GET' }
REQUEST make request http://localhost:8761/eureka/apps/
REQUEST onRequestResponse http://localhost:8761/eureka/apps/ 200 { server: 'Apache-Coyote/1.1',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  'content-length': '478',
  date: 'Mon, 09 May 2016 18:10:16 GMT',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function http://localhost:8761/eureka/apps/
REQUEST response end http://localhost:8761/eureka/apps/ 200 { server: 'Apache-Coyote/1.1',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  'content-length': '478',
  date: 'Mon, 09 May 2016 18:10:16 GMT',
  connection: 'close' }
REQUEST end event http://localhost:8761/eureka/apps/
REQUEST has body http://localhost:8761/eureka/apps/ 844
REQUEST emitting complete http://localhost:8761/eureka/apps/
retrieved registry successfully
complete
```

When I call the Eureka dashboard, I get an 500 Internal Server Error. The console output from the Eureka server:

```
2016-05-09 20:04:29.577 ERROR 813 --- [nio-8761-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.eureka.server.EurekaController.populateApps(EurekaController.java:236) ~[spring-cloud-netflix-eureka-server-1.1.0.RC2.jar:1.1.0.RC2]
	at org.springframework.cloud.netflix.eureka.server.EurekaController.status(EurekaController.java:68) ~[spring-cloud-netflix-eureka-server-1.1.0.RC2.jar:1.1.0.RC2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:261) ~[spring-boot-actuator-1.3.4.RELEASE.jar:1.3.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115) ~[spring-boot-actuator-1.3.4.RELEASE.jar:1.3.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103) ~[spring-boot-actuator-1.3.4.RELEASE.jar:1.3.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

Sorry for the trouble!

**Comment by danielbayerlein** [comment]
Workaround for this issue:

```js
    statusPageUrl: 'http://localhost:3001',
    healthCheckUrl: 'http://localhost:3001/health',
```

@jquatier Thanks for your great support!

**Comment by jquatier** [comment]
Cool. I didn't notice you weren't passing statusPageUrl, I'm guessing that's required, or something. Weird that it throws a NPE. Glad it's working!

**Comment by dileepkeeppalli** [comment]
@jquatier After I register my node service with eureka server When I try to access node api through api-gateway, getting this error Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: myApp.
