### ISSUE TITLE
Spring Cloud Neflix Support

### ISSUE THREAD

**Issue by mtheus** [jquatier/eureka-js-client#63]
Hello Friend! 

I'm almost giving up to use your API, can you help me do make a working example? 

1) Start our springcloud eureka app

`docker run -it -p 8761:8761 springcloud/eureka`

Check if it's up: [here](http://localhost:8761/)

2) Try to run my example:

```
var express = require('express');
var bodyParser = require('body-parser');

var app = express();
app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());

// ------------------ METHODS --------------------------------------------------

app.all('/', function (req, res) {
  var port = server.address().port;
  var msg = 'Hello Service ' + port;
  res.status(200);
  res.end(msg);
})

// ------------------ Eureka Config --------------------------------------------

// assuming no transpiler here
const Eureka = require('eureka-js-client').Eureka;

// example configuration
const eureka = new Eureka({
  // application instance information
  instance: {
    app: 'expressservice',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    port: 5000,
    vipAddress: 'localhost',
    dataCenterInfo: {
      name: 'MyOwn',
    }
  },
  eureka: {
    // eureka server host / port
    host: 'localhost',
    port: 8761,
  }
});
eureka.logger.level('debug');
eureka.start(function(error){
  console.log(error || 'complete');
});

// ------------------ Server Config --------------------------------------------
var server = app.listen(5000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Listening at http://%s:%s', host, port);
});

```

Now see my logs:

```
Listening at http://:::5000
REQUEST { url: 'http://localhost:8761/eureka/v2/apps/expressservice',
  json: true,
  body: 
   { instance: 
      { app: 'expressservice',
        hostName: 'localhost',
        ipAddr: '127.0.0.1',
        port: 5000,
        vipAddress: 'localhost',
        dataCenterInfo: [Object],
        status: 'UP' } },
  gzip: true,
  callback: [Function],
  method: 'POST' }
REQUEST make request http://localhost:8761/eureka/v2/apps/expressservice
REQUEST onRequestResponse http://localhost:8761/eureka/v2/apps/expressservice 404 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/json;charset=UTF-8',
  'transfer-encoding': 'chunked',
  date: 'Fri, 20 May 2016 13:16:18 GMT',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function http://localhost:8761/eureka/v2/apps/expressservice
REQUEST response end http://localhost:8761/eureka/v2/apps/expressservice 404 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/json;charset=UTF-8',
  'transfer-encoding': 'chunked',
  date: 'Fri, 20 May 2016 13:16:18 GMT',
  connection: 'close' }
REQUEST end event http://localhost:8761/eureka/v2/apps/expressservice
REQUEST has body http://localhost:8761/eureka/v2/apps/expressservice 122
REQUEST emitting complete http://localhost:8761/eureka/v2/apps/expressservice
Error starting the Eureka Client Error: eureka registration FAILED: status: 404 body: [object Object]
    at Request._callback (/projects/node_modules/eureka-js-client/lib/EurekaClient.js:270:25)
    at Request.self.callback (/projects/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/projects/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/projects/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
Error: eureka registration FAILED: status: 404 body: [object Object]
    at Request._callback (/projects/node_modules/eureka-js-client/lib/EurekaClient.js:270:25)
    at Request.self.callback (/projects/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/projects/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/projects/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

```

**Comment by jquatier** [comment]
This has come up a [couple](https://github.com/jquatier/eureka-js-client/issues/62) of [times](http://stackoverflow.com/questions/37188035/how-node-js-app-register-to-spring-eureka), so I added a section to the README [here](https://github.com/jquatier/eureka-js-client#404-not-found-errors-from-eureka-server).

I would modify the `eureka` section of your config to:

```
eureka: {
    // eureka server host / port
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps'
}
```

**Comment by mtheus** [comment]
Thanks for your answer: 

I tryed servicePath: '/eureka/apps' and a figure out this error above: ( missing "/" )

```
Listening at http://:::5000
REQUEST { url: 'http://localhost:8761/eureka/appsexpressservice',
  json: true,
  body: 
   { instance: 
      { app: 'expressservice',
        hostName: 'localhost',
        ipAddr: '127.0.0.1',
        port: 5000,
        vipAddress: 'localhost',
        dataCenterInfo: [Object],
        status: 'UP' } },
  gzip: true,
  callback: [Function],
  method: 'POST' }
(....)

```
So I Tryed 

`servicePath: '/eureka/apps/'`

And after that my eureka crashed: 

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Fri May 20 16:35:57 UTC 2016
> There was an unexpected error (type=Internal Server Error, status=500).
> No message available
> 

And in the LOG: 

```
  : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
  at org.springframework.cloud.netflix.eureka.server.EurekaController.populateApps(EurekaController.java:225)
  at org.springframework.cloud.netflix.eureka.server.EurekaController.status(EurekaController.java:60)
(......))

```
It's some thing missing in your protocol implementation?

**Comment by mtheus** [comment]
So I tryed to figure out in the code.. follow my analisys: 

1) https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java#L255
2) https://github.com/spring-cloud/spring-cloud-netflix/blob/5c2937b05c5aeeb9a4e3c180afffa674efdd9d8d/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java#L71
3) https://github.com/Netflix/eureka/blob/da2f9e5bcf2503487a52d839093f039bea065af2/eureka-core/src/main/java/com/netflix/eureka/resources/StatusResource.java#L57
4) https://github.com/Netflix/eureka/blob/da2f9e5bcf2503487a52d839093f039bea065af2/eureka-core/src/main/java/com/netflix/eureka/util/StatusUtil.java#L31

Could be something related with health check? How could I deal with this in the example?

**Comment by jquatier** [comment]
Alright, sounds like setting that service path worked because it's calling Eureka. I can assure you this client works with Spring Cloud, we have several groups using it that way. That error looks like its coming from the Spring Cloud code when it tried to download the full registry and parse all the applications. It still looks very similar to the issue reported [here](https://github.com/jquatier/eureka-js-client/issues/62) which I encourage you to read fully and use the code from. Try setting your `statusPageUrl` under `instance`.

```
statusPageUrl: 'http://localhost:5000',
```

If that still causes issues, you may want to try the newer style of configuration:

```
const client = new Eureka({
  instance: {
    app: 'myapp',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    statusPageUrl: 'http://localhost:5000',
    port: {
      '$': 5000,
      '@enabled': true,
    },
    vipAddress: 'myvip',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/',
  },
});
```

**Comment by mtheus** [comment]
Any ideas? 

Erros in the client: 

```
REQUEST emitting complete http://localhost:8761/eureka/apps/expressservice
Error starting the Eureka Client Error: eureka registration FAILED: status: 500 body: [object Object]
    at Request._callback (/projects/node_modules/eureka-js-client/lib/EurekaClient.js:270:25)
    at Request.self.callback (/projects/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/projects/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/projects/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
Error: eureka registration FAILED: status: 500 body: [object Object]
    at Request._callback (/projects/node_modules/eureka-js-client/lib/EurekaClient.js:270:25)
    at Request.self.callback (/projects/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/projects/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/projects/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

```


Errors in the Server: 



```
2016-05-20 17:13:20.179 ERROR 1 --- [nio-8761-exec-9] c.s.j.spi.container.ContainerResponse    : The RuntimeException could not be mapped to a response, re-throwing to the HTTP container

com.thoughtworks.xstream.converters.ConversionException: java.lang.Boolean cannot be cast to java.lang.String : java.lang.Boolean cannot be cast to java.lang.String
---- Debugging information ----
message             : java.lang.Boolean cannot be cast to java.lang.String
cause-exception     : java.lang.ClassCastException
cause-message       : java.lang.Boolean cannot be cast to java.lang.String
class               : com.netflix.appinfo.InstanceInfo
required-type       : com.netflix.appinfo.InstanceInfo
converter-type      : org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy$DataCenterAwareConverter
line number         : -1
version             : 1.1.147
-------------------------------
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy.unmarshal(DataCenterAwareMarshallingStrategy.java:71)
```


and ..


```
2016-05-20 17:13:20.181 ERROR 1 --- [nio-8761-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

com.thoughtworks.xstream.converters.ConversionException: java.lang.Boolean cannot be cast to java.lang.String : java.lang.Boolean cannot be cast to java.lang.String
---- Debugging information ----
message             : java.lang.Boolean cannot be cast to java.lang.String
cause-exception     : java.lang.ClassCastException
cause-message       : java.lang.Boolean cannot be cast to java.lang.String
class               : com.netflix.appinfo.InstanceInfo
required-type       : com.netflix.appinfo.InstanceInfo
converter-type      : org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy$DataCenterAwareConverter
line number         : -1
version             : 1.1.147
-------------------------------
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy.unmarshal(DataCenterAwareMarshallingStrategy.java:71)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:921)
    at com.netflix.discovery.converters.EntityBodyConverter.read(EntityBodyConverter.java:57)
    at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:94)

```

and ..

```
2016-05-20 17:13:20.181 ERROR 1 --- [nio-8761-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

com.thoughtworks.xstream.converters.ConversionException: java.lang.Boolean cannot be cast to java.lang.String : java.lang.Boolean cannot be cast to java.lang.String
---- Debugging information ----
message             : java.lang.Boolean cannot be cast to java.lang.String
cause-exception     : java.lang.ClassCastException
cause-message       : java.lang.Boolean cannot be cast to java.lang.String
class               : com.netflix.appinfo.InstanceInfo
required-type       : com.netflix.appinfo.InstanceInfo
converter-type      : org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy$DataCenterAwareConverter
line number         : -1
version             : 1.1.147
-------------------------------
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy.unmarshal(DataCenterAwareMarshallingStrategy.java:71)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:921)
    at com.netflix.discovery.converters.EntityBodyConverter.read(EntityBodyConverter.java:57)
    at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:94)

```

**Comment by mtheus** [comment]
Oh God.. 

```
    port: {
      '$': 5000,
      '@enabled': 'true',
    },
```

**Comment by jquatier** [comment]
Sweet. Glad you got it working!

**Comment by sperezme** [comment]
trying similar configuration i get this error

Listening at http://:::5000
Problem making eureka request { [Error: connect ECONNREFUSED 127.0.0.1:8761]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8761 }


Any ideas?

**Comment by sperezme** [comment]
const express = require('express');
const path = require('path');
const port = process.env.PORT || 3090;
const app = express();
app.use(express.static(__dirname));

const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());

app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'index.html'))
});

const Eureka = require('eureka-js-client').Eureka;

const eureka = new Eureka({
instance: {
    app: 'sheila',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    statusPageUrl: 'http://localhost:5000',
    healthCheckUrl: 'http://localhost:5000/health',
    port: {
      '$': 5000,
      '@enabled': 'true',
    },
    vipAddress: 'myvip',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/',
  },
});
eureka.logger.level('debug');
eureka.start(function(error){
 console.log(error || 'complete');
});

// ------------------ Server Config --------------------------------------------
var server = app.listen(5000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Listening at http://%s:%s', host, port);
});

**Comment by sperezme** [comment]
I am trying to run this locally after running  docker run -it -p 8761:8761 springcloud/eureka  on my local docker console.  In fact want i really want to achieve is to register this node.js service in my eureka-server in heroku. So far i can register a regular eureka-client demo without problems. But i am getting really confused with the configuration when the microservice is in node.js.    I thought eureka-js-client was the solution  for this, no success so far , any ideas?  :) :)

**Comment by jquatier** [comment]
Hey @sperezme, that connection error (`ECONNREFUSED 127.0.0.1:8761`), means that the module can't connect to Eureka at that host/port. Before doing anything in Node, or with this client, you'll need to figure out why the Eureka server isn't responding on port 8761. 

It looks like you are using docker to start a Eureka server on that port, so it's possible the service isn't running yet. I'd wait a couple minutes for the server to fully start, after you run the docker command. Try hitting the Eureka server REST service to see if it's running. This should be located at `http://localhost:8761/eureka/apps`. If that fails in your web browser or using `curl`, there's something else going on with your docker container and you'll need to check out the logs to see why the Eureka server isn't running. Hope this helps!
